# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3d6a27a6a9a4735964e00d3f663e7ebc2a5045a0c6c8ac690cb49f182c1d020f50155314b3f3b3d7e110953220889f6c66ac13eb152096cadd0d2111b20f075

test:
  secret_key_base: e45adaad5b1470ef65800eae475fd6fa501e582a207591b51a371f75fac27c6311dd3053a36284bec8a2c37160a32e99df1a6acda36f4ac8ff3a342e2680019e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
